[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
lazy_static = "1.4.0"
regex = "1.6.0"
thiserror = "1.0.31"

[dev-dependencies]
rand = "0.8.5"
